import type { Category } from '../types/category';

// Category colors (Tailwind classes)
export const CATEGORY_COLORS: Record<Category, string> = {
  Università: 'bg-blue-500',
  Vitto: 'bg-green-500',
  Abbigliamento: 'bg-purple-500',
  Casa: 'bg-yellow-500',
  Auto: 'bg-red-500',
  'Trasporti e viaggi': 'bg-indigo-500',
  'Bollette acqua': 'bg-cyan-500',
  'Bollette Luce': 'bg-amber-500',
  'Bollette Maddalena': 'bg-pink-500',
  Tasse: 'bg-gray-500',
  Sanità: 'bg-rose-500',
  Varie: 'bg-slate-500',
  Pulizie: 'bg-teal-500',
};

// Category icons (emoji)
export const CATEGORY_ICONS: Record<Category, string> = {
  Università: '🎓',
  Vitto: '🍽️',
  Abbigliamento: '👕',
  Casa: '🏠',
  Auto: '🚗',
  'Trasporti e viaggi': '✈️',
  'Bollette acqua': '💧',
  'Bollette Luce': '💡',
  'Bollette Maddalena': '📱',
  Tasse: '🏛️',
  Sanità: '⚕️',
  Varie: '📦',
  Pulizie: '🧹',
};

// Category keywords for intelligent parsing
export const CATEGORY_KEYWORDS: Record<Category, string[]> = {
  Università: [
    'università',
    'uni',
    'corso',
    'corsi',
    'libri universitari',
    'libro',
    'tasse universitarie',
    'tassa universitaria',
    'iscrizione',
    'esame',
    'materiale didattico',
  ],
  Vitto: [
    'supermercato',
    'spesa',
    'spese alimentari',
    'alimentari',
    'cibo',
    'ristorante',
    'pizzeria',
    'trattoria',
    'pranzo',
    'cena',
    'colazione',
    'bar',
    'caffè',
    'aperitivo',
    'cena fuori',
    'pranzo fuori',
    'deliveroo',
    'glovo',
    'just eat',
    'takeaway',
  ],
  Abbigliamento: [
    'vestiti',
    'vestito',
    'scarpe',
    'scarpa',
    'abbigliamento',
    'negozio abbigliamento',
    'camicia',
    'pantaloni',
    'giacca',
    'maglietta',
    'jeans',
    'cappotto',
    'borsa',
    'accessori',
  ],
  Casa: [
    'affitto',
    'casa',
    'mutuo',
    'condominio',
    'arredamento',
    'mobili',
    'mobile',
    'ikea',
    'bricolage',
    'riparazione casa',
    'manutenzione',
    'pittura',
    'lavori casa',
  ],
  Auto: [
    'benzina',
    'gasolio',
    'diesel',
    'auto',
    'automobile',
    'macchina',
    'parcheggio',
    'meccanico',
    'officina',
    'tagliando',
    'revisione',
    'assicurazione auto',
    'bollo',
    'bollo auto',
    'lavaggio auto',
    'autolavaggio',
    'gomme',
    'pneumatici',
  ],
  'Trasporti e viaggi': [
    'trasporti',
    'trasporto',
    'viaggio',
    'viaggi',
    'treno',
    'trenitalia',
    'italo',
    'aereo',
    'volo',
    'bus',
    'autobus',
    'pullman',
    'taxi',
    'uber',
    'biglietto',
    'abbonamento',
    'abbonamento trasporti',
    'metro',
    'metropolitana',
    'traghetto',
    'nave',
    'albergo',
    'hotel',
  ],
  'Bollette acqua': [
    'bolletta acqua',
    'acqua',
    'bolletta idrica',
    'servizio idrico',
    'acquedotto',
  ],
  'Bollette Luce': [
    'bolletta luce',
    'luce',
    'bolletta elettricità',
    'elettricità',
    'corrente',
    'energia elettrica',
    'enel',
    'eni',
    'acea',
  ],
  'Bollette Maddalena': [
    'bolletta maddalena',
    'maddalena',
  ],
  Tasse: [
    'tasse',
    'tassa',
    'imu',
    'tari',
    'imposte',
    'imposta',
    'irpef',
    'contributi',
    'f24',
  ],
  Sanità: [
    'medico',
    'dottore',
    'dott',
    'farmacia',
    'medicine',
    'medicina',
    'medicinale',
    'farmaco',
    'ospedale',
    'clinica',
    'salute',
    'analisi',
    'esami',
    'visita medica',
    'specialista',
    'dentista',
    'oculista',
  ],
  Varie: [
    'varie',
    'vari',
    'altro',
    'altri',
    'diversi',
    'vario',
  ],
  Pulizie: [
    'pulizie',
    'pulizia',
    'detersivi',
    'detersivo',
    'prodotti pulizia',
    'detergenti',
    'detergente',
    'candeggina',
    'sapone',
    'shampoo',
    'igiene',
    'carta igienica',
  ],
};

// Helper to get category info
export function getCategoryInfo(category: Category) {
  return {
    color: CATEGORY_COLORS[category],
    icon: CATEGORY_ICONS[category],
    keywords: CATEGORY_KEYWORDS[category],
  };
}
